sonar.organization=eulogep
sonar.projectKey=eulogep_double-calculatrice
sonar.projectName=double-calculatrice
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.mjs
sonar.exclusions=node_modules/**,coverage/**,_site/**,test-results/**,playwright-report/**,scripts/**,tests/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=main.js,advanced-features.js,tests/**,scripts/**
sonar.qualitygate.wait=true
